# Components (chip-agnostic)
set(CONFIG_BFLOG n)
set(CONFIG_FREERTOS y)
set(CONFIG_POSIX n)
set(CONFIG_TLSF y)
set(CONFIG_SHELL y)
set(CONFIG_LWIP y)
set(CONFIG_RF y)
set(CONFIG_MBEDTLS y)
# set(CONFIG_PSRAM y)
set(CONFIG_DHCPD y)
set(CONFIG_PING y)
# set(CONFIG_MQTT y)
set(CONFIG_BFLB_MTD y)
set(CONFIG_PARTITION y)
set(CONFIG_EASYFLASH4 y)

set(CONFIG_VSNPRINTF_FLOAT      y)
set(CONFIG_VSNPRINTF_FLOAT_EX   y)
set(CONFIG_VSNPRINTF_LONG_LONG  y)

# mbedtls
set(CONFIG_MBEDTLS_AES_USE_HW y)
set(CONFIG_MBEDTLS_BIGNUM_USE_HW y)
set(CONFIG_MBEDTLS_ECC_USE_HW y)
set(CONFIG_MBEDTLS_SHA1_USE_HW y)
set(CONFIG_MBEDTLS_SHA256_USE_HW y)
set(CONFIG_MBEDTLS_SHA512_USE_HW y)

# wifi caps used by lwipopts_user.h on all chips
# (BL616 / BL616CL bump these in their chip-specific block below)
set(CONFIG_MAC_TXQ_DEPTH 4)
set(CONFIG_MAC_RXQ_DEPTH 4)

# coex
set(CONFIG_COEX                  y)
set(CONFIG_COEX_WIFI_MODE        1)
set(CONFIG_COEX_BT_MODE          1)
set(CONFIG_COEX_TDMA_NONE        2)

# ble (common)
set(CONFIG_BLUETOOTH y)
set(CONFIG_BLE_USE_MAC2 n)
set(CONFIG_BLE_TP_SERVER y)
set(CONFIG_BLSYNC y)

# Chip-specific
if(CHIP STREQUAL "bl602")
    # wifi4 stack
    set(CONFIG_WIFI4 y)
    # 旧式 blecontroller
    set(CONFIG_BLECONTROLLER_LIB m1s1)
elseif(CHIP STREQUAL "bl616")
    set(CONFIG_WIFI6 y)
    set(CONFIG_FHOST y)
    set(CONFIG_MACSW_SELECT default)
    set(CONFIG_BTBLECONTROLLER_LIB ble1m10s1bredr0)
    set(CONFIG_VIF_MAX 2)
    set(CONFIG_STA_MAX 4)
    set(CONFIG_MAC_TXQ_DEPTH 16)
    set(CONFIG_MAC_RXQ_DEPTH 12)
elseif(CHIP STREQUAL "bl616cl")
    set(CONFIG_WIFI6 y)
    set(CONFIG_FHOST y)
    set(CONFIG_MACSW_SELECT default)
    set(CONFIG_BTBLECONTROLLER_LIB m2s1)
    set(CONFIG_VIF_MAX 2)
    set(CONFIG_STA_MAX 4)
    set(CONFIG_MAC_TXQ_DEPTH 16)
    set(CONFIG_MAC_RXQ_DEPTH 12)
else()
    message(FATAL_ERROR "Unsupported CHIP: ${CHIP}")
endif()
