# This file is generated automatically by : python menuconfig.py -s /home/zxf10/at-project/project/ameba/prj.conf
CONFIG_PLATFORM_FREERTOS=y
CONFIG_BT_MENU=y
CONFIG_MBEDTLS_SSL_PROTO_TLS1_3_MENU=y
CONFIG_MBEDTLS_THREADING=y
